sentence_list=[
    "It was a really good Monday for being a Saturday",
    "She was amazed by the large chunks of ice washing up on the beach",
    "He went on a whiskey diet and immediately lost three days",
    "You bite up because of your lower jaw",
    "She cried diamonds",
    "Gwen had her best sleep ever on her new bed of nails",
    "The family’s excitement over going to Disneyland was crazier than she anticipated",
    "You realize you're not alone as you sit in your bedroom massaging your calves after a long day of playing tug-of-war with Grandpa Joe in the hospital",
    "If eating three-egg omelets causes weight-gain, budgie eggs are a good substitute",
    "They wandered into a strange Tiki bar on the edge of the small beach town",
    "Smoky the Bear secretly started the fires",
    "She is never happy until she finds something to be unhappy about; then, she is overjoyed",
    "I purchased a baby clown from the Russian terrorist black market",
    "She looked at the masterpiece hanging in the museum but all she could think is that her five-year-old could do better",
    "Getting up at dawn is for the birds",
    "The pigs were insulted that they were named hamburgers",
    "The shark-infested South Pine channel was the only way in or out",
    "Lets all be unique together until we realise we are all the same",
    "I like to leave work after my eight-hour tea-break",
    "If you like tuna and tomato sauce, try combining the two, it’s really not as bad as it sounds",
    "There should have been a time and a place, but this wasn't it",
    "The clouds formed beautiful animals in the sky that eventually created a tornado to wreak havoc",
    "His confidence would have bee admirable if it wasn't for his stupidity",
    "Even though he thought the world was flat he didn’t see the irony of wanting to travel around the world",
    "The doll spun around in circles in hopes of coming alive",
    "After coating myself in vegetable oil I found my success rate skyrocketed"
    "Check back tomorrow, I will see if the book has arrived",

]